### ISSUE TITLE
Drupal rule error

### ISSUE THREAD

**Issue by deliant** [nbs-system/naxsi-rules#17]
2016/03/11 00:32:02 [emerg] 13063#0: Naxsi-Config : Incorrect line BasicRule wl:1310,1311 (/build/nginx-BU0ZJt/nginx-1.4.6/debian/modules/naxsi/naxsi_src/naxsi_skeleton.c/393)... in /etc/nginx/naxsi.drupal:21

On ubuntu 14.04lts

**Comment by buixor** [comment]
hello,

can you confirm it happens with current ruleset ?
should have been resolved.
