### ISSUE TITLE
Naxsi Wordpress rules blocks theme live preview in customizer

### ISSUE THREAD

**Issue by webimbue** [nbs-system/naxsi-rules#31]
The naxsi wordpress rules seem to block the live preview of any other installed themes except for the active one. But when  connection to naxsi WAF is closed by commeting out the "include" line in the config file, the live preview starts to work fine. 
The entries in my nginx log regarding the preview blocking is something like this:

`2016/08/09 18:59:55 [error] 6315#6315: *11957 NAXSI_FMT: ip=1.2.3.4&server=www.example.com&uri=/&learning=0&vers=0.55rc2&total_processed=77&total_blocked=4&block=1&zone0=BODY&id0=2&var_name0=, client: 1.2.3.4, server: www.example.com, request: "POST / HTTP/1.1", host: "www.example.com", referrer: "http://www.example.com/wp-admin/customize.php?theme=twentytwelve&return=%2Fwp-admin%2Fthemes.php"`

Is there any rule white listing that needs to be done? If yes then please update. I am not able to figure it out.
I am facing this issue with both "wordpress-rules" and "wordpress-minimal" rulesets

**Comment by Doemela** [comment]
###	Theme customize + customize header
BasicRule  wl:1001,1015,1101,1310,1311 "mz:$URL_X:^/.*$|$BODY_VAR_X:^customized$|BODY";
###	Widget customize
BasicRule  wl:1001,1015,1310,1311 "mz:$URL_X:^/.*$|$BODY_VAR_X:^partials$|BODY";

**Comment by webimbue** [comment]
@Doemela Thank you very much for your response. Also my apologies, for not responding timely to your help. Yes you have rightly said that the issue is witth "id0=2" that is big request. and the reason for that was a very low value assigned to 'client_body_buffer_size' parameter in my 'nginx.conf' file. I  updated a value of '16k' asgainst 'client_body_buffer_size' and the errors are gone and the live preview and customizer is working really well. 
Ref : 'http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_buffer_size'
Thank you once again...!!! :)
