### ISSUE TITLE
Match Pattern search string load from file

### ISSUE THREAD

**Issue by vncloudsco** [nbs-system/naxsi-rules#36]
Match Pattern only activated str and rx, I want to put values Match Pattern beforce creat rules.  i want load contents file to Match Pattern? Since this value is so much, it is troublesome to enumerate them on a rule. 

You can get a look at my ideas when using modsecutity with the feature pmFromFile (ref: https://docs.huihoo.com/modsecurity/2.5.7/operators.html)

Does anyone have a way to do this?

**Comment by wargio** [comment]
DUP
