### ISSUE TITLE
msg not activated in log errors.

### ISSUE THREAD

**Issue by vncloudsco** [nbs-system/naxsi-rules#38]
I have checked nasxi's logs and don't see my msg set in rules. How can I add this information to my log.

my rules:
```
MainRule  "str:mj12bot" "msg:mj12bot - UA Detected" "mz:$HEADERS_VAR:User-Agent" "s:$UWA:8" id:42000386  ;

```

full log: 

```
2021/04/08 11:03:00 [error] 14308#14308: *3955 NAXSI_FMT: ip=x.x.x.x&server=x.x.x.x&uri=/&learning=0&vers=0.56&total_processed=21&total_blocked=6&block=1&cscore0=$SQL&score0=2&cscore1=$XSS&score1=8&zone0=BODY|NAME&id0=1002&var_name0=0x%5B%5D&zone1=BODY|NAME&id1=1310&var_name1=0x%5B%5D&zone2=BODY|NAME&id2=1311&var_name2=0x%5B%5D, client: x.x.x.x, server: x.com, request: "POST / HTTP/1.1", host: "x.com"
```

**Comment by wargio** [comment]
as stated in the wiki, `msg:` field is like a comment. you won't see it in the logs, because logs are limited at 1024 chars (unless you change the NGINX code and rebuild)

**Comment by vncloudsco** [comment]
@wargio it doesn't have 1024 characters you can check, I tested it for only about 400 characters.

**Comment by wargio** [comment]
i made a mistake, t's 2k https://github.com/nginx/nginx/blob/7e1637a31631955aec753365c7149c64b216d47e/src/core/ngx_log.h#L76

**Comment by vncloudsco** [comment]
@wargio Even so you can see that all of my logs cannot exceed such a quota. How can I add information to my log?

**Comment by wargio** [comment]
you have to change the code

**Comment by wargio** [comment]
i don't see any reason to do this
when you can just parse the rules and parse the logs and match comments with ids
