### ISSUE TITLE
javascript injection and XSS rules

### ISSUE THREAD

**Issue by esaheiskanen** [nbs-system/naxsi-rules#5]
Should there be rulesets for javascript / jquery?

Sample jquery selector vulnerability: 
`http://domain.tld/#panel2<img src=M onerror='alert("Hello")'>hi</a>`

**Comment by buixor** [comment]
Hi,

naxsi-rules only provides whitelists for application.
Plus, from the URL, it seems to be a dom-based XSS

**Comment by esaheiskanen** [comment]
Thank you for answer. 

If I understand correctly Dom-based XSS  could also be cleaned with Naxsi?

**Comment by buixor** [comment]
Hi,

Actually, I didn't look at the vulnerability itself, however - usually -
DOM Based XSS can't be stopped by a WAF, as the payload (after the #) is
never sent to the browser, but just used locally by the browser.
